services:
  - type: web
    name: jewelry-hamza-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma generate && npx prisma migrate deploy && npx ts-node prisma/seed.ts
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: file:./prisma/prod.db
